import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import { AbsoluteImg } from "./components/shared/absolute-img";
import { GradientShadow } from "./components/shared/gradient-shadow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mypay",
  description: "Generated by mypay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className='bg-[#00020D] relative min-h-screen px-4 md:px-0'>
          <GradientShadow className="top-[5%] left-[8.4%]" />
          <GradientShadow className="top-[5%] right-[10%]" />
          <Navbar />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
